### ISSUE TITLE
Scheme issue

### ISSUE THREAD

**Issue by thebitstick** [Francesco149/gweet#1]
``` bash
Makoto :: ~/.sharenix % ~/.sharenix/sharenix -m="fs"                           
Debug: Parsing config...
Taking screenshot...
Debug: Using 1 screens
Debug: 0    X: 0    Y: 0    Width: 1366 Height: 768
Debug: Building 1366 x 768 image
Debug: Drawing (0,0)-(1366,768)
Uploading to Twitter
Debug: gweet map[_tails:$input$]
Post gweet: unsupported protocol scheme ""
```

**Comment by Francesco149** [comment]
hmm it seems like you got your parameter name wrong in the sharenix settings. it's _tail, not _tails .
also it's pretty weird that it's not replacing $input$ , but maybe it's just because I print out the map before it actually gets replaced. See if changing _tails to _tail in your json file fixes the problem.

**Comment by Francesco149** [comment]
I took a quick look at my own code and it seems it's an issue with sharenix not replacing $input$ in screenshots and should only happen when taking full-screen screenshots. I will fix this asap.
your parameter name is definitely wrong tho so you might also wanna fix that.

**Comment by Francesco149** [comment]
fixed and tested in https://github.com/Francesco149/sharenix/commit/c2edd4c2bc70f3ad380dfddf0c6dea299c434f39

you will have to compile from source or wait a day or two though, cause I can't build binaries right now
